# Generated by Django 4.0.6 on 2022-08-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0003_uzivatel_alter_film_options_alter_zanr_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=30, verbose_name='Tagy')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagy',
            },
        ),
        migrations.AlterField(
            model_name='film',
            name='nazev',
            field=models.CharField(max_length=200, verbose_name='Název Filmu'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rezie',
            field=models.CharField(max_length=180, verbose_name='Režie'),
        ),
        migrations.AlterField(
            model_name='film',
            name='zanr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviebook.zanr', verbose_name='Žánr'),
        ),
        migrations.AddField(
            model_name='film',
            name='tagy',
            field=models.ManyToManyField(to='moviebook.tag'),
        ),
    ]
